name: Deploy in PROD environment
run-name: ${{ github.actor }} is deploying to PROD environment 🚀
on: 
  release:
    types: [created]


env:
  ENV: prod 
  IMAGE_NAME: isis-api
  DOCKERHUB_NAMESPACE: osirisagitech
  APPLICATION_PORT: 4040

jobs:
  build-and-push-image:
    name: Build and Publish Image on Dockerhub
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ env.DOCKERHUB_NAMESPACE }}/${{ env.IMAGE_NAME }}:${{ github.event.release.tag_name }}

  pull-image:
    name: Pull Image
    runs-on: ubuntu-latest
    needs: build-and-push-image
    steps:
      - name: Establishing SSH connection to remote machine
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST_SSH }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: 22
          script: |
            echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login --username ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
            docker pull ${{ env.DOCKERHUB_NAMESPACE }}/${{ env.IMAGE_NAME }}:${{ github.event.release.tag_name }}

  run-container:
    name: Up Container
    runs-on: ubuntu-latest
    needs: pull-image
    steps:
      - name: Run Docker container
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST_SSH }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            docker stop ${{ env.IMAGE_NAME }}-${{ env.ENV }} || true
            docker rm ${{ env.IMAGE_NAME }}-${{ env.ENV }} || true
            docker run -d --name ${{ env.IMAGE_NAME }}-${{ env.ENV }} \
              -e DATABASE_URL=${{ secrets.DATABASE_URL_PROD }} -e APP_PORT=${{ env.APPLICATION_PORT }} \
              -p ${{ env.APPLICATION_PORT }}:${{ env.APPLICATION_PORT }} \
              ${{ env.DOCKERHUB_NAMESPACE }}/${{ env.IMAGE_NAME }}:${{ github.event.release.tag_name }}
